### ISSUE TITLE
Geting the data by census tract

### ISSUE THREAD

**Issue by JoelEmbiiddddd** [jiawlu/OSM2GMNS#11]
Hi~, I am so interested in this package and i want to know could it obtain the data of the poi by census tract?

**Comment by jiawlu** [comment]
@JoelEmbiiddddd Glad to know you are interested in our tools. Now, osm2gmns does not provide such data, but we are happy to incorporate various functionalities into our package to accommodate user needs. Can you provide more details on the data you are requesting?
