### ISSUE TITLE
Retrieving additional fields from OSM

### ISSUE THREAD

**Issue by pedrocamargo** [jiawlu/OSM2GMNS#12]
For many use cases, it is important to get information on additional tags from OSM. One example is to identify tunnels and bridges.

So, ideally, the API would allow for something like:

`og.getNetFromFile("asu.osm.pbf", tags=["bridge", "tunnel"])`

**Comment by jiawlu** [comment]
@pedrocamargo Thanks for your suggestion. We will keep improving our tool

**Comment by pedrocamargo** [comment]
Hi. I got the notification that this has been completed. Is this the case?  Is there documentation on how to use the feature?

**Comment by jiawlu** [comment]
@pedrocamargo Sorry for the confusion. We do not have such features now, but I have put your suggestion in our development roadmap. I closed the ticket here.

**Comment by pedrocamargo** [comment]
Oh, my misunderstanding. The usual practice is to keep issues for new features open, as that avoids other people filling the same issue and also allows other people to see that the feature is needed and to make a Pull request to meet that request, but there are different ways of managing things!

Is the development roadmap publicly available?
