### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'tb_frame'

### ISSUE THREAD

**Issue by radi2015** [jiawlu/OSM2GMNS#23]
curl http://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf -o barefoot/map/osm/oberbayern.osm.pbf

net = og.getNetFromFile('oberbayern.osm.pbf')

AttributeError: 'tuple' object has no attribute 'tb_frame'

**Comment by jiawlu** [comment]
I'm not able to reproduce the issue. The command you provided runs well on my side. Please make sure you are using the latest version of osm2gmns
