### ISSUE TITLE
AttributeError: module 'osm2gmns' has no attribute 'connectPOIWithNet'

### ISSUE THREAD

**Issue by d-camargo** [jiawlu/OSM2GMNS#3]
Hi, everyone.
The latest version of osm2gmns that I've got (by 'pip install osm2gmns') was 0.6.3, this error appear:
**AttributeError: module 'osm2gmns' has no attribute 'connectPOIWithNet'**

I did the downgrade to 0.6.2 and I got the same error. My code was:

```
import osm2gmns as og 
net = og.getNetFromOSMFile('cefet_ns.osm', default_lanes=True, POI=True)
og.connectPOIWithNet(net)
og.generateNodeActivityInfo(net)
og.consolidateComplexIntersections(net)
og.generateMovements(net)
og.outputNetToCSV(net)
og.show(net)
```

PS.: I'm using PyCharm to process. The argument 'POIs' (in the second line of the code), as it is in the documentation bring another error: 
net = og.getNetFromOSMFile('cefet_ns.osm', default_lanes=True, POIs=True)
TypeError: getNetFromOSMFile() got an unexpected keyword argument 'POIs'
After use 'POI' the argument error disappear.

Something has changed on the use of connectPOIWithNet?

**Comment by jiawlu** [comment]
Hi,

Thanks for reporting the bug. We will fix the function `connectPOIWithNet()` in the next release.
